# Generated by Django 5.0.7 on 2024-07-12 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0002_remove_user_is_active_remove_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
    ]
